<?php

namespace WebserviceBundle\Repository;

/**
 * CapturaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CapturaRepository extends \Doctrine\ORM\EntityRepository
{
}
