<?php

namespace WebserviceBundle\Repository;

/**
 * PuntuacionOfertaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PuntuacionOfertaRepository extends \Doctrine\ORM\EntityRepository
{
}
