webservice:
    resource: "@WebserviceBundle/Controller/"
    type:     annotation
    prefix:   /

categoria:
    type: rest
    resource: WebserviceBundle\Controller\CategoriaController

usuario:
    type: rest
    resource: WebserviceBundle\Controller\UsuarioController

comentario:
    type: rest
    resource: WebserviceBundle\Controller\ComentarioController

oferta:
    type: rest
    resource: WebserviceBundle\Controller\OfertaController

app:
    resource: '@AppBundle/Controller/'
    type: annotation
