webservice:
    resource: "@WebserviceBundle/Controller/"
    type:     annotation
    prefix:   /

categoria:
    type: rest
    resource: WebserviceBundle\Controller\CategoriaController

app:
    resource: '@AppBundle/Controller/'
    type: annotation
