webservice:
    resource: "@WebserviceBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

categoria:
    type: rest
    resource: WebserviceBundle\Controller\CategoriaController

usuario:
    type: rest
    resource: WebserviceBundle\Controller\UsuarioController

comentario:
    type: rest
    resource: WebserviceBundle\Controller\ComentarioController

puntuacion:
    type: rest
    resource: WebserviceBundle\Controller\PuntuacionController

<<<<<<< HEAD
puntuacion:
    type: rest
    resource: WebserviceBundle\Controller\PuntuacionController

app:
    resource: '@AppBundle/Controller/'
    type: annotation
=======
oferta:
    type: rest
    resource: WebserviceBundle\Controller\OfertaController
>>>>>>> kappa
